NUMERIC_COLUMNS = ["FTE", "Total"]
CATEGORIES = [
    "Function",
    "Use",
    "Sharing",
    "Reporting",
    "Student_Type",
    "Position_Type",
    "Object_Type",
    "Pre_K",
    "Operating_Status",
]
LABELS = [
    "Function_Aides Compensation",
    "Function_Career & Academic Counseling",
    "Function_Communications",
    "Function_Curriculum Development",
    "Function_Data Processing & Information Services",
    "Function_Development & Fundraising",
    "Function_Enrichment",
    "Function_Extended Time & Tutoring",
    "Function_Facilities & Maintenance",
    "Function_Facilities Planning",
    "Function_Finance, Budget, Purchasing & Distribution",
    "Function_Food Services",
    "Function_Governance",
    "Function_Human Resources",
    "Function_Instructional Materials & Supplies",
    "Function_Insurance",
    "Function_Legal",
    "Function_Library & Media",
    "Function_NO_LABEL",
    "Function_Other Compensation",
    "Function_Other Non-Compensation",
    "Function_Parent & Community Relations",
    "Function_Physical Health & Services",
    "Function_Professional Development",
    "Function_Recruitment",
    "Function_Research & Accountability",
    "Function_School Administration",
    "Function_School Supervision",
    "Function_Security & Safety",
    "Function_Social & Emotional",
    "Function_Special Population Program Management & Support",
    "Function_Student Assignment",
    "Function_Student Transportation",
    "Function_Substitute Compensation",
    "Function_Teacher Compensation",
    "Function_Untracked Budget Set-Aside",
    "Function_Utilities",
    "Use_Business Services",
    "Use_ISPD",
    "Use_Instruction",
    "Use_Leadership",
    "Use_NO_LABEL",
    "Use_O&M",
    "Use_Pupil Services & Enrichment",
    "Use_Untracked Budget Set-Aside",
    "Sharing_Leadership & Management",
    "Sharing_NO_LABEL",
    "Sharing_School Reported",
    "Sharing_School on Central Budgets",
    "Sharing_Shared Services",
    "Reporting_NO_LABEL",
    "Reporting_Non-School",
    "Reporting_School",
    "Student_Type_Alternative",
    "Student_Type_At Risk",
    "Student_Type_ELL",
    "Student_Type_Gifted",
    "Student_Type_NO_LABEL",
    "Student_Type_Poverty",
    "Student_Type_PreK",
    "Student_Type_Special Education",
    "Student_Type_Unspecified",
    "Position_Type_(Exec) Director",
    "Position_Type_Area Officers",
    "Position_Type_Club Advisor/Coach",
    "Position_Type_Coordinator/Manager",
    "Position_Type_Custodian",
    "Position_Type_Guidance Counselor",
    "Position_Type_Instructional Coach",
    "Position_Type_Librarian",
    "Position_Type_NO_LABEL",
    "Position_Type_Non-Position",
    "Position_Type_Nurse",
    "Position_Type_Nurse Aide",
    "Position_Type_Occupational Therapist",
    "Position_Type_Other",
    "Position_Type_Physical Therapist",
    "Position_Type_Principal",
    "Position_Type_Psychologist",
    "Position_Type_School Monitor/Security",
    "Position_Type_Sec/Clerk/Other Admin",
    "Position_Type_Social Worker",
    "Position_Type_Speech Therapist",
    "Position_Type_Substitute",
    "Position_Type_TA",
    "Position_Type_Teacher",
    "Position_Type_Vice Principal",
    "Object_Type_Base Salary/Compensation",
    "Object_Type_Benefits",
    "Object_Type_Contracted Services",
    "Object_Type_Equipment & Equipment Lease",
    "Object_Type_NO_LABEL",
    "Object_Type_Other Compensation/Stipend",
    "Object_Type_Other Non-Compensation",
    "Object_Type_Rent/Utilities",
    "Object_Type_Substitute Compensation",
    "Object_Type_Supplies/Materials",
    "Object_Type_Travel & Conferences",
    "Pre_K_NO_LABEL",
    "Pre_K_Non PreK",
    "Pre_K_PreK",
    "Operating_Status_Non-Operating",
    "Operating_Status_Operating, Not PreK-12",
    "Operating_Status_PreK-12 Operating",
]
