name: train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/train.py -c config/hyperparameters.yml
      # - run: mkdir -p path/to/artifact
      # - run: echo hello > path/to/artifact/world.txt
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: path/to/artifact/world.txt
